apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- configmap.yaml
images:
- name: serret18/web-frontend
  newName: serret18/web-frontend
  newTag: 22c756d31636fbbe77997e978316ee802b4fd106
