apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- configmap.yaml
- ./secret.yaml
images:
- name: serret18//web-frontend
  newName: serret18//web-frontend
  newTag: c26da62662c2860f1c0b3e022256cd74b86c86be
