apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- configmap.yaml
patches:
- path: ./limits.yaml
- path: ./tolerations.yaml
images:
- name: serret18/web-frontend
  newName: serret18/web-frontend
  newTag: 03efcdac7565fd79669f6b63156dc428f012ab6b
