apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- configmap.yaml
images:
- name: serret18/web-frontend
  newName: serret18/web-frontend
  newTag: 161e84ad20a90a3be7fefa32783cfc4719c3b87b
