apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- configmap.yaml
patches:
- path: ./limits.yaml
- path: ./tolerations.yaml
images:
- name: serret18/web-frontend
  newName: serret18/web-frontend
  newTag: 0f892569b0e26c296bfebd8c1dc216c85d23174c
