apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- configmap.yaml
patches:
- path: ./limits.yaml
- path: ./tolerations.yaml
images:
- name: serret18/web-frontend-production
  newName: serret18/web-frontend-production
  newTag: 80f2a9ee76754a9e47da4748bd56e74a6cfd97c6
