apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- hpa.yaml
- configmap.yaml
- ./secret.yaml
patches:
- path: ./limits.yaml
- path: ./tolerations.yaml
images:
- name: serret18/web-frontend-production
  newName: serret18/web-frontend-production
  newTag: fcc70be6c2d0533eb4434b4529858f532dff01eb
