apiVersion: v1
kind: Service
metadata:
  name: web-frontend-production-svc
  labels:
    app: web-frontend-production
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5173
  selector:
    app: web-frontend-production
  type: ClusterIP
