apiVersion: v1  # Versión de la API de Kubernetes que se está utilizando para definir este recurso.
kind: Service  # Tipo de recurso que se está creando, en este caso, un Service para exponer la aplicación.
metadata:
  name: web-frontend-svc  # Nombre del Service que se está creando.
  labels:
    app: web-frontend  # Etiqueta que se asigna al Service para identificarlo.
spec:
  ports:
    - name: http  # Nombre del puerto expuesto por el Service.
      port: 80  # Número de puerto que escuchará el Service dentro del clúster.
      targetPort: 5173  # Puerto del contenedor al que se dirigirán las solicitudes.
  selector:
    app: web-frontend  # Selector que indica qué Pods deben ser seleccionados por este Service.
  type: ClusterIP  # Tipo de Service, en este caso, ClusterIP, que proporciona una IP interna para acceder al Service dentro del clúster.
