apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-backend-argocd-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: api-backend-argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Backend/api-backend-prod/overlays/production
    repoURL: https://github.com/BootCampDevOpsProject/GitOps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
