apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-frontend-argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: web-frontend-argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Frontend/web-frontend/overlays/production
    repoURL: https://github.com/BootCampDevOpsProject/GitOps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
