apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#- ingress.yaml
resources:
- ../../base
- configmap.yaml
#- ./secret.yaml
images:
- name: serret18/api-backend
  newName: serret18/api-backend
  newTag: 6012cb0e9bffdbe395ee33508942f45a03d48523
