apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- configmap.yaml
patches:
- path: ./limits.yaml
- path: ./tolerations.yaml
images:
- name: serret18/api-backend
  newName: serret18/api-backend
  newTag: ea852e0d3840d31d7e73f7effb70f3eb19b39d6e
