apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- hpa.yaml
- configmap.yaml
patches:
- path: ./limits.yaml
- path: ./tolerations.yaml
images:
- name: serret18/api-backend
  newName: serret18/api-backend
  newTag: da250cf320ecc11614bdbadbfdf2bf41546f1bbe
