apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#- ingress.yaml
resources:
- ../../base
- configmap.yaml
#- ./secret.yaml
images:
- name: serret18/api-backend
  newName: serret18/api-backend
  newTag: 03b004db59ca2144fb32a3e05bb32fb597bf4bce
