apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- configmap.yaml
patches:
- path: ./limits.yaml
- path: ./tolerations.yaml
images:
- name: serret18/api-backend-production
  newName: serret18/api-backend-production
  newTag: 05fac25e425f3d449ed21aa0174f5021acc5e46b
