apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- hpa.yaml
- configmap.yaml
patches:
- path: ./limits.yaml
- path: ./tolerations.yaml
- path: ./patch.yaml
images:
- name: serret18/api-backend-production
  newName: serret18/api-backend-production
  newTag: ca4153a7da5632a633ded8f1ed9d5cbd5bd51d87
