apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend-production
spec:
  template:
    spec:
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "prod"
          effect: "NoSchedule"