apiVersion: apps/v1
kind: Deployment
metadata:
  name: #project_name#
  annotations:
    configmap.reloader.stakater.com/reload: "#project_name#-configmap" 
    secret.reloader.stakater.com/reload: "#project_name#-secret"
spec:
  selector:
    matchLabels:
      app: #project_name#
  template:
    metadata:
      labels:
        app: #project_name#
    spec:
      containers:
        - name: #project_name#
          envFrom:
            - configMapRef:
                name: #project_name#-configmap
            - secretRef:
                name: #project_name#-secret
          image: #dcokerhub_repo_name/#project_name#
          imagePullPolicy: Always
          ports:
            - containerPort: #PORT#
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: #RUTA_HEALTH#
              port: #PORT#
            initialDelaySeconds: 5
            periodSeconds: 60
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: #RUTA_HEALTH#
              port: #PORT#
            periodSeconds: 60
      imagePullSecrets:
        - name: docker-registry
