apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
  annotations:
    configmap.reloader.stakater.com/reload: "api-backend-configmap" 
    #secret.reloader.stakater.com/reload: "api-backend-secret"
spec:
  selector:
    matchLabels:
      app: api-backend
  template:
    metadata:
      labels:
        app: api-backend
    spec:
      containers:
        - name: api-backend
          envFrom:
            - configMapRef:
                name: api-backend-configmap
           #- secretRef:
              #  name: api-backend-secret
          image: serret18/api-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
