apiVersion: v1
kind: Service
metadata:
  name: api-backend-svc
  labels:
    app: api-backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: api-backend
  type: ClusterIP
